### ISSUE TITLE
More info please

### ISSUE THREAD

**Issue by Pamposgsk** [razorcreations/nova-ajax-field#7]
Could you please give some more detail to use this package.
By using the searchable() method in a BelongsTo field Iam getting the desired result but is slow.
As far as I understand your package overcomes this problem and can make a BelongTo field to show faster the results.
Is that correct?

**Comment by rossjcooper** [comment]
Hi @Pamposgsk the idea behind this was to provide a field that could use results from an AJAX request rather than having to be tied specifically to a model or a relationship. 
This way pretty much anything can be returned in the AJAX response and stored as a field.
Hopefully the readme covers a lot of how to do this but if there is anything specific you need help with please provide some example's and we'll do our best to advise.
